---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: cfktopic1
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 1
  configs:
    cleanup.policy: "delete"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: produce-message
spec:
  replicas: 1
  selector:
    matchLabels:
      app: produce-app
  template:
    metadata:
      labels:
        app: produce-app
    spec:
      containers:
      - name: produce-data-container
        image: anirudh2903/topicproduce:latest
        volumeMounts:
        - name: kafka-properties
          mountPath: /mnt
        resources:
          requests:
            memory: 512Mi
            cpu: 500m