apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: source-connector
  namespace: confluent
spec:
  class: io.confluent.connect.jdbc.JdbcSourceConnector
  taskMax: 1
  configs:
    connector.class: "io.confluent.connect.jdbc.JdbcSourceConnector"
    connection.url: "jdbc:postgresql://postgres:5432/users"
    connection.user: "postgres"
    connection.password: "postgres"
    mode: "incrementing"
    topic.prefix: "postgres_"
    incrementing.column.name: "user_id"
    table.whitelist: "userdata"
    poll.interval.ms: "5000"
    key.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter: "io.confluent.connect.avro.AvroConverter"
    key.converter.schema.registry.url: "http://schemaregistry.confluent.svc.cluster.local:8081"
    value.converter.schema.registry.url: "http://schemaregistry.confluent.svc.cluster.local:8081"