apiVersion: v1
kind: Pod
metadata:
  name: topic-creator
spec:
  containers:
  - name: topic-creator
    image: confluentinc/cp-kafka:latest
    command:
    - /bin/sh
    - -c
    args: 
    - |
      kafka-topics \
      --bootstrap-server kafka-0.kafka.confluent.svc.cluster.local:9092,kafka-1.kafka.confluent.svc.cluster.local:9092 \
      --create --topic cfktopic1 \
      --partitions 2 --replication-factor 2

  restartPolicy: Never

